import type {
  PlaygroundDefinition,
  PlaygroundControl,
} from '@alkemdotdev/alkemist-components/playground';
const text = (name: string, help?: string): PlaygroundControl => ({
  name,
  type: 'text',
  help,
});
const area = (name: string, help?: string): PlaygroundControl => ({
  name,
  type: 'textarea',
  help,
});
const bool = (name: string): PlaygroundControl => ({ name, type: 'boolean' });
const json = (name: string, help?: string): PlaygroundControl => ({
  name,
  type: 'json',
  help,
});
const select = (name: string, options: string[]): PlaygroundControl => ({
  name,
  type: 'select',
  options,
});
const number = (
  name: string,
  min: number,
  max: number,
  step = 1,
): PlaygroundControl => ({ name, type: 'number', min, max, step });
const component = (
  id: string,
  name: string,
  defaults: PlaygroundDefinition['defaults'],
  controls: PlaygroundControl[],
  presets?: PlaygroundDefinition['presets'],
  textSlotProp?: string,
): PlaygroundDefinition => ({
  id,
  name,
  importPath: `@alkemdotdev/alkemist-components/${id}`,
  defaults,
  controls,
  presets,
  textSlotProp,
});
const headings = [
  { depth: 2, slug: 'introduction', text: 'Introduction' },
  { depth: 3, slug: 'first-example', text: 'First example' },
  { depth: 2, slug: 'reference', text: 'Reference' },
];
const items = [
  { label: 'Getting started', href: '/docs/' },
  {
    label: 'Components',
    href: '/docs/components/',
    children: [
      { label: 'Content', href: '/docs/content/' },
      { label: 'Visualization', href: '/docs/visualization/' },
    ],
  },
];
const posts = [
  {
    href: '/blog/',
    title: 'Making ideas visible',
    description: 'An experiment in publishing research.',
    date: '2026-09-13',
    cover: { src: '/test/torus-knot.svg', alt: 'A torus knot', fit: 'contain' },
  },
  {
    href: '/labs/',
    title: 'An interactive notebook',
    description: 'Small experiments you can inspect.',
    date: '2026-09-12',
  },
  {
    href: '/docs/',
    title: 'Document the useful parts',
    description: 'A reference that grows with the work.',
    date: '2026-09-11',
    cover: { src: '/test/torus-knot.svg', alt: 'Knot diagram' },
  },
];
export const definitions: Record<string, PlaygroundDefinition> = {
  html: {
    id: 'html',
    name: 'HTML',
    defaults: {
      type: 'paragraph',
      text: 'A useful idea starts with a clear explanation.',
      items: ['Observe', 'Build', 'Explain'],
      headers: ['Quantity', 'Value'],
      rows: [
        ['Frequency', '2 Hz'],
        ['Damping', '0.12'],
      ],
      summary: 'Read the experiment notes',
      label: 'Experiment name',
      inputType: 'text',
      value: '',
      placeholder: 'Name your experiment',
      open: false,
      ordered: false,
      checked: false,
      disabled: false,
    },
    controls: [
      select('type', [
        'paragraph',
        'heading-2',
        'heading-3',
        'blockquote',
        'list',
        'table',
        'details',
        'button',
        'input',
      ]),
      area('text'),
      json('items', 'List items, used by the list example.'),
      json('headers', 'Table column headings.'),
      json('rows', 'Table data rows.'),
      text('summary'),
      text('label'),
      select('inputType', [
        'text',
        'email',
        'number',
        'checkbox',
        'search',
        'url',
      ]),
      text('value'),
      text('placeholder'),
      bool('open'),
      bool('ordered'),
      bool('checked'),
      bool('disabled'),
    ],
  },
  image: {
    id: 'image',
    name: 'img',
    defaults: {
      src: '/test/torus-knot.svg',
      alt: 'A blue torus knot',
      width: 720,
      height: 400,
      fit: 'contain',
      caption: 'A generated geometric teaching specimen.',
    },
    controls: [
      text('src'),
      text('alt'),
      number('width', 80, 1600),
      number('height', 80, 1200),
      select('fit', ['contain', 'cover']),
      text('caption'),
    ],
  },
  'native-audio': {
    id: 'native-audio',
    name: 'audio',
    defaults: {
      src: '/test/tone.wav',
      autoplay: false,
      muted: false,
      loop: false,
      preload: 'metadata',
    },
    controls: [
      text('src'),
      bool('autoplay'),
      bool('muted'),
      bool('loop'),
      select('preload', ['none', 'metadata', 'auto']),
    ],
  },
  'native-video': {
    id: 'native-video',
    name: 'video',
    defaults: {
      src: '/test/waves.mp4',
      poster: '',
      width: 640,
      autoplay: false,
      muted: true,
      loop: true,
      preload: 'metadata',
    },
    controls: [
      text('src'),
      text('poster'),
      number('width', 160, 1600),
      bool('autoplay'),
      bool('muted'),
      bool('loop'),
      select('preload', ['none', 'metadata', 'auto']),
    ],
  },
  audio: component(
    'audio',
    'Audio',
    {
      src: '/test/media-study.wav',
      title: 'Three tones',
      caption: 'A synthetic 30-second listening study.',
      preload: 'metadata',
      autoplay: false,
      muted: false,
      loop: false,
      playbackRates: [0.5, 0.75, 1, 1.25, 1.5, 2],
      seekOffset: 10,
      tracks: [
        {
          src: '/test/media-chapters.vtt',
          kind: 'chapters',
          srclang: 'en',
          label: 'Sections',
        },
      ],
      download: true,
      transcript:
        '0:00 — A quiet 220 Hz tone.\n0:10 — The tone rises to 330 Hz.\n0:20 — The tone rises to 440 Hz, then fades out.',
    },
    [
      text('src'),
      text('title'),
      text('caption'),
      select('preload', ['none', 'metadata', 'auto']),
      bool('autoplay'),
      bool('muted'),
      bool('loop'),
      json('playbackRates'),
      number('seekOffset', 1, 60),
      json('tracks'),
      bool('download'),
      area('transcript'),
    ],
    [
      {
        label: 'Minimal',
        values: {
          title: '',
          caption: '',
          tracks: [],
          transcript: '',
          download: false,
        },
      },
      {
        label: 'Listening study',
        values: { loop: true, seekOffset: 5, playbackRates: [0.5, 1, 1.5, 2] },
      },
    ],
  ),
  video: component(
    'video',
    'Video',
    {
      src: '/test/media-study.mp4',
      title: 'Wave study',
      caption:
        'Synthetic motion and tones, with two caption languages and three chapters.',
      poster: '/test/media-poster.jpg',
      preload: 'metadata',
      autoplay: false,
      muted: true,
      loop: false,
      playbackRates: [0.5, 0.75, 1, 1.25, 1.5, 2],
      seekOffset: 10,
      tracks: [
        {
          src: '/test/media-en.vtt',
          kind: 'captions',
          srclang: 'en',
          label: 'English',
          default: true,
        },
        {
          src: '/test/media-es.vtt',
          kind: 'subtitles',
          srclang: 'es',
          label: 'Español',
        },
        {
          src: '/test/media-chapters.vtt',
          kind: 'chapters',
          srclang: 'en',
          label: 'Sections',
        },
      ],
      download: true,
      transcript:
        '0:00 — Blue waves drift across the frame over a low tone.\n0:10 — The tone rises as the wave pattern continues.\n0:20 — The final higher tone fades out with the study.',
    },
    [
      text('src'),
      text('title'),
      text('caption'),
      text('poster'),
      select('preload', ['none', 'metadata', 'auto']),
      bool('autoplay'),
      bool('muted'),
      bool('loop'),
      json('playbackRates'),
      number('seekOffset', 1, 60),
      json('tracks'),
      bool('download'),
      area('transcript'),
    ],
    [
      { label: 'With captions', values: { muted: true } },
      {
        label: 'Silent loop',
        values: {
          autoplay: true,
          muted: true,
          loop: true,
          tracks: [],
          transcript: '',
          download: false,
        },
      },
    ],
  ),
  math: component(
    'math',
    'Math',
    { tex: 'E = mc^2', display: true, label: 'Mass–energy equivalence' },
    [area('tex'), bool('display'), text('label')],
    [
      {
        label: 'Integral',
        values: {
          tex: '\\int_0^1 x^2 \\, dx = \\frac{1}{3}',
          display: true,
          label: 'A definite integral',
        },
      },
      {
        label: 'Inline',
        values: { tex: 'a^2+b^2=c^2', display: false, label: '' },
      },
    ],
  ),
  code: component(
    'code',
    'Code',
    {
      code: 'const damping = 0.25;\nconst frequency = 2;\nconst duration = 10;\nconst samples = 300;\n\nconst omegaD = frequency * Math.sqrt(1 - damping ** 2);\nconst displacement = (t: number) =>\n  Math.exp(-damping * frequency * t) * Math.cos(omegaD * t);\n\nconst points = Array.from({ length: samples }, (_, i) => {\n  const time = (i / (samples - 1)) * duration;\n  return { time, value: displacement(time) };\n});',
      lang: 'typescript',
      title: 'oscillator.ts',
      highlightLines: [],
      lineNumbers: true,
      focusLines: [],
      addedLines: [],
      removedLines: [],
      collapsedRanges: [],
      annotations: [],
      highlightText: [],
      wrap: false,
    },
    [
      area('code'),
      text('lang', 'Any language bundled with Shiki, or text.'),
      text('title'),
      bool('lineNumbers'),
      bool('wrap'),
      json('highlightLines', 'One-based line numbers, e.g. [6, 7, 8].'),
      json('focusLines', 'Keep these lines prominent; dim the rest.'),
      json('addedLines', 'Lines marked as additions.'),
      json('removedLines', 'Lines marked as removals.'),
      json('collapsedRanges', 'Ranges: [{"start":1,"end":4,"label":"Setup"}].'),
      json(
        'annotations',
        'Notes: [{"line":6,"text":"Damped angular frequency."}].',
      ),
      json('highlightText', 'Exact text to mark, e.g. ["omegaD"].'),
    ],
    [
      {
        label: 'Explain',
        values: {
          collapsedRanges: [{ start: 1, end: 4, label: 'Oscillator settings' }],
          highlightLines: [6],
          highlightText: ['omegaD'],
          annotations: [
            { line: 6, text: 'Damping reduces the natural angular frequency.' },
          ],
        },
      },
      { label: 'Focus', values: { focusLines: [6, 7, 8] } },
      {
        label: 'Changes',
        values: {
          code: 'const samples = 100;\nconst samples = 300;\nconst duration = 10;',
          removedLines: [1],
          addedLines: [2],
        },
      },
      {
        label: 'Python',
        values: {
          code: 'frequency = 2\nperiod = 1 / frequency',
          lang: 'python',
          title: 'oscillator.py',
          highlightLines: [2],
        },
      },
      {
        label: 'Plain text',
        values: {
          code: 'Observe → build → explain',
          lang: 'text',
          title: 'notes.txt',
          lineNumbers: false,
        },
      },
    ],
    'code',
  ),
  chart: component(
    'chart',
    'Chart',
    {
      src: '/test/oscillation.csv',
      type: 'line',
      x: 'time',
      y: 'position',
      title: 'A damped oscillator',
      description: 'Synthetic data with damping ratio 0.12.',
      xLabel: 'Time (s)',
      yLabel: 'Position (m)',
      xType: 'quantitative',
      color: '',
      colorLabel: '',
      value: '',
      valueLabel: '',
      ink: 'cobalt',
      height: 280,
      grid: true,
      zoom: true,
      horizontal: false,
      stacked: false,
      caption: '',
      sample: true,
    },
    [
      select('type', ['line', 'bar', 'scatter', 'pie', 'donut', 'heatmap']),
      text('src', 'CSV URL. Presets select a matching dataset and fields.'),
      text('x'),
      text('y'),
      text('title'),
      area('description'),
      text('xLabel'),
      text('yLabel'),
      select('xType', ['quantitative', 'temporal', 'nominal', 'ordinal']),
      text('color', 'Optional column for groups or series.'),
      text('colorLabel'),
      text('value', 'Required for heatmap.'),
      text('valueLabel'),
      select('ink', [
        'cobalt',
        'cyan',
        'teal',
        'fern',
        'ochre',
        'vermilion',
        'rose',
        'violet',
      ]),
      number('height', 120, 900),
      bool('grid'),
      bool('zoom'),
      bool('horizontal'),
      bool('stacked'),
      text('caption'),
      bool('sample'),
    ],
    [
      { label: 'Line', values: { type: 'line' } },
      { label: 'Scatter', values: { type: 'scatter' } },
      ...['bar', 'pie', 'donut'].map((type) => ({
        label: type[0].toUpperCase() + type.slice(1),
        values: {
          type,
          src: '/test/materials.csv',
          x: 'material',
          y: 'value',
          xType: 'nominal',
          title: 'Prototype materials',
          description: 'Synthetic counts by material.',
          xLabel: 'Material',
          yLabel: 'Count',
        },
      })),
      {
        label: 'Heatmap',
        values: {
          type: 'heatmap',
          src: '/test/field.csv',
          x: 'x',
          y: 'y',
          value: 'value',
          xType: 'ordinal',
          title: 'An analytic field',
          description: 'A synthetic scalar field.',
          xLabel: 'x',
          yLabel: 'y',
          valueLabel: 'Field value',
        },
      },
    ],
  ),
  model: component(
    'model',
    'Model',
    {
      src: '/test/torus-knot.glb',
      title: 'A torus knot',
      description: 'Drag to inspect this generated teaching mesh.',
      poster: '/test/torus-knot.svg',
      class: '',
    },
    [
      text('src'),
      text('title'),
      area('description'),
      text('poster'),
      text('class', 'A CSS class supplied by your own site.'),
    ],
  ),
  shader: component(
    'shader',
    'Shader',
    { title: 'Two wave sources', frequency: 9, angle: 24, class: '' },
    [
      text('title'),
      number('frequency', 3, 18, 0.1),
      number('angle', 0, 180),
      text('class'),
    ],
    [
      { label: 'Fine contours', values: { frequency: 16, angle: 90 } },
      { label: 'Broad waves', values: { frequency: 4, angle: 0 } },
    ],
  ),
  navigation: component(
    'navigation',
    'Navigation',
    {
      items,
      currentPath: '/docs/content/',
      label: 'Example navigation',
      expandedDepth: 1,
      headings,
    },
    [
      json('items', 'Nested {label, href, children?} records.'),
      text('currentPath'),
      text('label'),
      number('expandedDepth', 0, 8),
      json('headings'),
    ],
  ),
  'table-of-contents': component(
    'table-of-contents',
    'TableOfContents',
    { headings, label: 'On this page', showLabel: true },
    [
      json(
        'headings',
        '{depth, slug, text} records; preview headings are generated to match.',
      ),
      text('label'),
      bool('showLabel'),
    ],
  ),
  'post-list': component(
    'post-list',
    'PostList',
    {
      items: posts,
      layout: 'featured-grid',
      selectable: true,
      featuredHref: '',
      label: 'Recent work',
    },
    [
      json(
        'items',
        'Posts with href, title, description, optional date and cover {src, alt, fit, focalX, focalY}.',
      ),
      select('layout', ['rows', 'featured', 'grid', 'featured-grid']),
      bool('selectable'),
      text('featuredHref'),
      text('label'),
    ],
  ),
  search: component(
    'search',
    'Search',
    {
      indexUrl: '/pagefind/pagefind.js',
      placeholder: 'Search the documentation',
      label: 'Search this site',
      variant: 'standalone',
    },
    [
      text('indexUrl', 'Pagefind runtime URL. Requires a built index.'),
      text('placeholder'),
      text('label'),
      select('variant', ['standalone', 'header']),
    ],
  ),
  layout: {
    ...component(
      'layout',
      'Layout',
      {
        title: 'Research notes',
        description: 'A place for experiments and explanations.',
        section: 'docs',
        preview: false,
        siteName: 'My lab',
        tagline: 'research in public',
        faviconHref: '/favicon.svg',
        navigation: [
          { label: 'Home', href: '/' },
          { label: 'Docs', href: '/docs/' },
        ],
        moreNavigation: [{ label: 'Labs', href: '/labs/' }],
        footerNavigation: [{ label: 'About', href: '/info/' }],
        search: false,
      },
      [
        text('title'),
        area('description'),
        text('section'),
        bool('preview'),
        text('siteName'),
        text('tagline'),
        text('faviconHref'),
        json('navigation'),
        json('moreNavigation'),
        json('footerNavigation'),
        json('search', 'false, true, or Search props.'),
      ],
    ),
    slot: '<h1>Research notes</h1>\n<p>A place for experiments and explanations.</p>',
  },
};

export const groups = [
  {
    id: 'content',
    title: 'Content',
    description:
      'Publish equations, source code, audio, and video with reusable components.',
    examples: ['math', 'code', 'audio', 'video'],
  },
  {
    id: 'visualization',
    title: 'Visualization',
    description:
      'Make datasets inspectable, with charts, labels, tables, and source files.',
    examples: ['chart'],
  },
  {
    id: 'graphics',
    title: 'Graphics',
    description:
      'Explore three-dimensional models and interactive shader studies.',
    examples: ['model', 'shader'],
  },
  {
    id: 'website',
    title: 'Website',
    description:
      'Compose a complete site from layouts, navigation, collections, and search.',
    examples: [
      'layout',
      'navigation',
      'table-of-contents',
      'post-list',
      'search',
    ],
  },
];

/** Native elements are theme references, not component package exports. */
export const nativeContent = {
  id: 'native-content',
  title: 'Native HTML & media',
  description:
    'Standard browser elements styled by the Alkemist theme. No wrapper components or component imports required.',
  examples: ['html', 'image', 'native-audio', 'native-video'],
};
